const Data = [
  {
    id: 1,
    category: "education",
    icon: "icon-graduation",
    year: "2021 - present",
    title: "BTech in Electronics and Communication Engineering",
    desc: "Currently pursuing BTech in Electronics and Communication Engineering from GGSIPU, New Delhi.",
    url: "",
  },
  {
    id: 2,
    category: "education",
    icon: "icon-graduation",
    year: "2023 - 2024",
    title: "Google UX Design Professional Certificate",
    desc: "Google UX Design Professional Certificate covering essential UX design principles and practices.",
    url: "https://www.coursera.org/account/accomplishments/professional-cert/9Z3HPCG68AMX",
  },
  {
    id: 3,
    category: "education",
    icon: "icon-graduation",
    year: "2023",
    title: "Blender Creator: 3D Modelling",
    desc: "Introduction to 3D modeling using Blender facilitated by gamedev.tv on Udemy.",
    url: "https://www.udemy.com/certificate/UC-d4e0ef3b-775c-45a2-ba65-51274102ba5a/",
  },
  {
    id: 4,
    category: "education",
    icon: "icon-graduation",
    year: "2023",
    title: "Meta Creator Course",
    desc: "Learned to create immersive experiences on the Meta platform through practical projects.",
    url: "https://www.bornoninstagram.com/student/award/dppSWAGBgXNGvk4iwHRFfFXQ",
  },
  {
    id: 5,
    category: "education",
    icon: "icon-graduation",
    year: "2023",
    title: "Plasticity Modelling Course",
    desc: "Advanced techniques in 3D modeling with a focus on plasticity modeling by Arrimus 3D on Udemy.",
    url: "https://www.udemy.com/certificate/UC-5c4a1400-be60-46b2-b45c-8f6230ac2e43/",
  },
  {
    id: 6,
    category: "education",
    icon: "icon-graduation",
    year: "2023",
    title: "C# 2D Game Development in Unity",
    desc: "Hands-on approach to game development using Unity and C# facilitated by gamedev.tv on Udemy.",
    url: "https://www.udemy.com/certificate/UC-b1745b28-c150-4db4-9bdc-9454163c5974/",
  },
];

export default Data;
